apiVersion: v1                     # API group for core Kubernetes objects
kind: ServiceAccount               # We are creating a ServiceAccount
metadata:
  name: jenkins-sa                 # Name of the ServiceAccount used by Jenkins
  namespace: jenkins               # Namespace where Jenkins runs
---
apiVersion: rbac.authorization.k8s.io/v1   # API group for role-based access control
kind: ClusterRoleBinding                   # Binds a ClusterRole to a user/SA across the cluster
metadata:
  name: jenkins-sa-cluster-admin           # Name of this ClusterRoleBinding object
roleRef:
  apiGroup: rbac.authorization.k8s.io      # API group where the ClusterRole exists
  kind: ClusterRole                         # Type of role we are binding
  name: cluster-admin                       # The role we are granting (full cluster access)
subjects:
  - kind: ServiceAccount                    # The subject receiving the permissions is a ServiceAccount
    name: jenkins-sa                        # Name of the ServiceAccount that gets access
    namespace: jenkins                      # Namespace where the ServiceAccount exists

