---
apiVersion: rbac.authorization.k8s.io/v1      # API group for RBAC resources
kind: ClusterRole                              # Creates a custom cluster-wide role
metadata:
  name: jenkins-admin                          # Name of this custom ClusterRole
rules:
  - apiGroups: [""]                            # "" means the core API group (Pods, Services, ConfigMaps, etc.)
    resources: ["*"]                           # Allows access to ALL resource types in this API group
    verbs: ["*"]                               # Allows ALL actions (get, list, watch, create, delete, patch, etc.)
---
apiVersion: v1                                 # API group for core objects
kind: ServiceAccount                           # Creates a ServiceAccount for Jenkins
metadata:
  name: jenkins-admin                          # Name of the ServiceAccount Jenkins will use
  namespace: jenkins                           # Namespace where Jenkins and the SA exist
---
apiVersion: rbac.authorization.k8s.io/v1       # RBAC API group
kind: ClusterRoleBinding                       # Grants the ClusterRole to a user/SA cluster-wide
metadata:
  name: jenkins-admin                          # Name of this ClusterRoleBinding
roleRef:
  apiGroup: rbac.authorization.k8s.io          # API group for the referenced role
  kind: ClusterRole                            # Binding is for a ClusterRole
  name: jenkins-admin                          # The ClusterRole being assigned
subjects:
- kind: ServiceAccount                         # The subject receiving these permissions is a ServiceAccount
  name: jenkins-admin                          # Name of the ServiceAccount that gets admin permissions
  namespace: jenkins                           # Namespace where the ServiceAccount lives

